language: node_js
node_js:
 - "node"
before_script: 
  - "psql -c \"CREATE DATABASE social_streets;\" -U postgres"
  - "psql -c \"CREATE USER social_streets WITH PASSWORD '123';\" -U postgres"
  - "cd server && npm i"
env: 
  global: 
  - PGPORT=5432
services: 
  - postgresql
test: 
  adapter: postgresql
  database: social_streets
